/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Model.VideoObject;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author E6540
 */
public class VideoContent extends javax.swing.JPanel {

    /**
     * Creates new form Video
     */
    private VideoObject objV;
    private String linkDownload;
    public VideoContent(VideoObject obj) {
        initComponents();
        this.panel_video.setBackground(new Color(0, 0, 0, 0));
        this.panel_video.setVisible(true);
        this.objV = obj;
        ImageIcon img = new ImageIcon(ResizeImg(objV.getImgPreviewVideo(), 290));
        this.lbl_videoThumb.setIcon(img);
        this.lbl_heart.setText(String.valueOf(objV.getHeartNums()));
        this.lbl_cmt.setText(String.valueOf(objV.getCmtNums()));
        this.lbl_share.setText(String.valueOf(objV.getShareNums()));
        this.linkDownload = obj.getLinkDownload();
        this.lbl_download.setEnabled(false);
        this.lbl_download.setVisible(false);
        this.progressbar.setVisible(false);
        
    }

    public Image ResizeImg(ImageIcon imgIcon, int px) {
        return imgIcon.getImage().getScaledInstance(-1, px, Image.SCALE_SMOOTH);
    }
    
    public void downloadThisVideo()
    {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save this Video");   

        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            reqDownloadAndSaveFile(filePath);
        }
    }
    
    public void reqDownloadAndSaveFile(String fPath)
    {
        try {
            URL url = new URL(linkDownload);
            URLConnection urlConn = url.openConnection();
            urlConn.setConnectTimeout(30000);
            urlConn.setReadTimeout(30000);
            urlConn.setAllowUserInteraction(false);
            InputStream inputStream = urlConn.getInputStream();
            int lenghtOfFile = urlConn.getContentLength();   
            byte[] videoBuffer = new byte[512];

            File file = new File(fPath);
            FileOutputStream fileOutputStream = new FileOutputStream(file);
            int len;
            long total = 0;
            this.progressbar.setVisible(true);
            this.lbl_download.setEnabled(false);
            while ((len = inputStream.read(videoBuffer)) != -1) {
                total+=len;
                fileOutputStream.write(videoBuffer, 0, len);
                this.progressbar.setValue((int)((total*100)/lenghtOfFile));
            }
            this.progressbar.setString("Success");
            this.lbl_download.setEnabled(true);
            //Close the file stream
            fileOutputStream.close();

            //Done message
            System.out.println("Video Downloaded!");
        } catch (MalformedURLException ex) {
            
        } catch (IOException ex) {
           
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredpane_video = new javax.swing.JLayeredPane();
        panel_video = new javax.swing.JPanel();
        lbl_download = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_heart = new javax.swing.JLabel();
        lbl_share = new javax.swing.JLabel();
        lbl_cmt = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        lbl_videoThumb = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(150, 290));
        setMinimumSize(new java.awt.Dimension(150, 290));
        setPreferredSize(new java.awt.Dimension(150, 290));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        layeredpane_video.setMaximumSize(new java.awt.Dimension(150, 290));
        layeredpane_video.setMinimumSize(new java.awt.Dimension(150, 290));
        layeredpane_video.setName(""); // NOI18N
        layeredpane_video.setLayout(new javax.swing.OverlayLayout(layeredpane_video));

        panel_video.setBackground(new java.awt.Color(0, 0, 0));
        panel_video.setAlignmentX(0.5F);
        panel_video.setAlignmentY(0.5F);
        panel_video.setMaximumSize(new java.awt.Dimension(150, 290));
        panel_video.setMinimumSize(new java.awt.Dimension(150, 290));
        panel_video.setPreferredSize(new java.awt.Dimension(150, 290));
        panel_video.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_download.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_download.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        lbl_download.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_download.setMaximumSize(new java.awt.Dimension(40, 40));
        lbl_download.setMinimumSize(new java.awt.Dimension(40, 40));
        lbl_download.setPreferredSize(new java.awt.Dimension(40, 40));
        lbl_download.setRequestFocusEnabled(false);
        lbl_download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_downloadMouseClicked(evt);
            }
        });
        panel_video.add(lbl_download, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/heart.png"))); // NOI18N
        panel_video.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cmt.png"))); // NOI18N
        panel_video.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/share.png"))); // NOI18N
        panel_video.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        lbl_heart.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_heart.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heart.setText("999999");
        panel_video.add(lbl_heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 84, 23));

        lbl_share.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_share.setForeground(new java.awt.Color(255, 255, 255));
        lbl_share.setText("999999");
        panel_video.add(lbl_share, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 84, 23));

        lbl_cmt.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_cmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cmt.setText("999999");
        panel_video.add(lbl_cmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 84, 20));
        panel_video.add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        layeredpane_video.add(panel_video);

        lbl_videoThumb.setAlignmentX(0.5F);
        lbl_videoThumb.setMaximumSize(new java.awt.Dimension(150, 290));
        lbl_videoThumb.setMinimumSize(new java.awt.Dimension(150, 290));
        lbl_videoThumb.setPreferredSize(new java.awt.Dimension(150, 290));
        layeredpane_video.add(lbl_videoThumb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layeredpane_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(layeredpane_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_downloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_downloadMouseClicked
        downloadThisVideo();
    }//GEN-LAST:event_lbl_downloadMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
         this.lbl_download.setEnabled(true);
        this.lbl_download.setVisible(true);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.lbl_download.setEnabled(false);
        this.lbl_download.setVisible(false);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane layeredpane_video;
    private javax.swing.JLabel lbl_cmt;
    private javax.swing.JLabel lbl_download;
    private javax.swing.JLabel lbl_heart;
    private javax.swing.JLabel lbl_share;
    private javax.swing.JLabel lbl_videoThumb;
    private javax.swing.JPanel panel_video;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}
